[package]
name = "adaptive-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
chain-types.workspace = true
market-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
