[package]
name = "rpc-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build = "=0.14.5"
tonic-build = "=0.14.5"

[dev-dependencies]
tokio = { workspace = true }
